const Lookbook_Data = [{
    id: "lookbook_1",
    background_src: "./img/lookbook/lookbook_1_background.jpg",
    stand_src: "./img/lookbook/lookbook_1_stand_off.png",
    stand_data: ["237px", "638px"],
    item1_src: "./img/lookbook/lookbook_1_item_1.png",
    item2_src: "./img/lookbook/lookbook_1_item_2.png",
    item3_src: "./img/lookbook/lookbook_1_item_3.png",
    item1_data: ["96px", "71px", "658px", "15px"],
    item2_data: ["197px", "264px", "647px", "88px"],
    item3_data: ["152px", "151px", "633px", "335px"],
    item1_desc: ["TYLER BUCKET HAT", "YUCCA", "₩ 103,000"],
    item2_desc: ["S/S MASTER SHIRT", "TEIDE", "₩ 113,000"],
    item3_desc: ["REGULAR CARGO SHORT COLUMBIA", "BUFFALO RINSED", "₩ 138,000"],
    item1_url: "https://carhartt-wip.co.kr/product/142863",
    item2_url: "https://carhartt-wip.co.kr/product/142987",
    item3_url: "https://carhartt-wip.co.kr/product/143141"
  },
  {
    id: "lookbook_2",
    background_src: "./img/lookbook/lookbook_2_background.jpg",
    stand_src: "./img/lookbook/lookbook_2_stand_off.png",
    stand_data: ["178px", "625px"],
    item1_src: "./img/lookbook/lookbook_2_item_1.png",
    item2_src: "./img/lookbook/lookbook_2_item_2.png",
    item3_src: "./img/lookbook/lookbook_2_item_3.png",
    item1_data: ["102px", "80px", "616px", "13px"],
    item2_data: ["166px", "269px", "628px", "99px"],
    item3_data: ["152px", "209px", "605px", "242px"],
    item1_desc: ["ELWAY BUCKET HAT", "DOLLAR GREEN", "₩ 103,000"],
    item2_desc: ["W S/S COBA SHIRT", "WHITE", "₩ 208,000"],
    item3_desc: ["W TRISTIN SHORT", "BLACK RINSED", "₩ 138,000"],
    item1_url: "https://carhartt-wip.co.kr/product/142799",
    item2_url: "https://carhartt-wip.co.kr/product/143447",
    item3_url: "https://carhartt-wip.co.kr/product/139695"
  },
  {
    id: "lookbook_3",
    background_src: "./img/lookbook/lookbook_3_background.jpg",
    stand_src: "./img/lookbook/lookbook_3_stand_off.png",
    stand_data: ["176px", "636px"],
    item1_src: "./img/lookbook/lookbook_3_item_1.png",
    item2_src: "./img/lookbook/lookbook_3_item_2.png",
    item3_src: "./img/lookbook/lookbook_3_item_3.png",
    item1_data: ["63px", "36px", "621px", "13px"],
    item2_data: ["178px", "241px", "622px", "106px"],
    item3_data: ["139px", "301px", "620px", "317px"],
    item1_desc: ["MADISON LOGO CAP", "BLACK", "₩ 68,000"],
    item2_desc: ["S/S COIN T-SHIRT", "ARCADE/SUNRISE", "₩ 83,000"],
    item3_desc: ["BRANDON PANT SMITH", "BLUE STONE BLEACHED", "₩ 165,000"],
    item1_url: "https://carhartt-wip.co.kr/product/142710",
    item2_url: "https://carhartt-wip.co.kr/product/143011",
    item3_url: "https://carhartt-wip.co.kr/product/143173"
  }
];

const shoppingList_Top = [{
    id: "top_ts_m_01",
    name: "반팔 라이프가즈 티셔츠",
    subname: "S/S LIFEGUARDS T-SHIRT",
    category: ["top", "tshirt"],
    gender: "male",
    price: 75000,
    src: ["./img/top/top_ts_m_01/front_black.jpg", "./img/top/top_ts_m_01/back_black.jpg"],
    color: ["black", "white", "yellow"],
    isOut: false,
    isBest: true,
    isNew: true,
    discountRate: 0
  },
  {
    id: "top_ts_m_02",
    name: "반팔 이노베이션 포켓 티셔츠",
    subname: "S/S INNOVATION POCKET T-SHIRT",
    category: ["top", "tshirt"],
    gender: "male",
    price: 85000,
    src: ["./img/top/top_ts_m_02/front_white.jpg", "./img/top/top_ts_m_02/back_white.jpg"],
    color: ["white", "black", "grey"],
    isOut: false,
    isBest: true,
    isNew: true,
    discountRate: 0
  },
  {
    id: "top_ts_m_03",
    name: "반팔 버커루 티셔츠",
    subname: "S/S BUCKAROO T-SHIRT",
    category: ["top", "tshirt"],
    gender: "male",
    price: 78000,
    src: ["./img/top/top_ts_m_03/front_brown.jpg", "./img/top/top_ts_m_03/back_brown.jpg"],
    color: ["brown", "white", "green"],
    isOut: false,
    isBest: true,
    isNew: true,
    discountRate: 0
  },
  {
    id: "top_ts_m_04",
    name: "반팔 부기 티셔츠",
    subname: "S/S BOOGIE T-SHIRT",
    category: ["top", "tshirt"],
    gender: "male",
    price: 78000,
    src: ["./img/top/top_ts_m_04/front_yellow.jpg", "./img/top/top_ts_m_04/back_yellow.jpg"],
    color: ["yellow", "white", "grey"],
    isOut: false,
    isBest: true,
    isNew: false,
    discountRate: 0,
  },
  {
    id: "top_jacket_m_01",
    name: "코스탈 자켓",
    subname: "COASTAL JACKET",
    category: ["top", "jacket"],
    gender: "male",
    price: 248000,
    src: ["./img/top/top_jacket_m_01/front_black.jpg", "./img/top/top_jacket_m_01/back_black.jpg"],
    color: ["black", "white"],
    isOut: false,
    isBest: true,
    isNew: true,
    discountRate: 0
  },
  {
    id: "top_jacket_m_02",
    name: "살레도 자켓",
    subname: "SALEDO JACKET",
    category: ["top", "jacket"],
    gender: "male",
    price: 208000,
    src: ["./img/top/top_jacket_m_02/front_blue.jpg", "./img/top/top_jacket_m_02/back_blue.jpg"],
    color: ["blue", "black"],
    isOut: false,
    isBest: true,
    isNew: true,
    discountRate: 0
  },
  {
    id: "top_jacket_m_03",
    name: "알링 자켓",
    subname: "ARLING JACKET",
    category: ["top", "jacket"],
    gender: "male",
    price: 368000,
    src: ["./img/top/top_jacket_m_03/front_black.jpg", "./img/top/top_jacket_m_03/back_black.jpg"],
    color: ["black", "blue"],
    isOut: false,
    isBest: true,
    isNew: true,
    discountRate: 0
  },
  {
    id: "top_jacket_m_04",
    name: "알마 자켓",
    subname: "ALMA JACKET",
    category: ["top", "jacket"],
    gender: "male",
    price: 298000,
    src: ["./img/top/top_jacket_m_04/front_black.jpg", "./img/top/top_jacket_m_04/back_black.jpg"],
    color: ["black"],
    isOut: false,
    isBest: true,
    isNew: true,
    discountRate: 0
  },
  {
    id: "top_s_m_01",
    name: "반팔 블랙 잭 셔츠",
    subname: "S/S BLACK JACK SHIRT",
    category: ["top", "shirt"],
    gender: "male",
    price: 143000,
    src: ["./img/top/top_s_m_01/front_white.jpg", "./img/top/top_s_m_01/back_white.jpg"],
    color: ["black", "black"],
    isOut: false,
    isBest: true,
    isNew: true,
    discountRate: 0
  },
  {
    id: "top_s_m_02",
    name: "반팔 바유 셔츠",
    subname: "S/S BAYOU SHIRT",
    category: ["top", "shirt"],
    gender: "male",
    price: 143000,
    src: ["./img/top/top_s_m_02/front_red.jpg", "./img/top/top_s_m_02/back_red.jpg"],
    color: ["red", "blue"],
    isOut: false,
    isBest: true,
    isNew: true,
    discountRate: 0
  },
  {
    id: "top_s_m_03",
    name: "반팔 델레이 셔츠",
    subname: "S/S DELRAY SHIRT",
    category: ["top", "shirt"],
    gender: "male",
    price: 118000,
    src: ["./img/top/top_s_m_03/front_blue.jpg", "./img/top/top_s_m_03/back_blue.jpg"],
    color: ["blue", "grey", "red", "black"],
    isOut: false,
    isBest: true,
    isNew: true,
    discountRate: 0
  },
  {
    id: "top_s_m_04",
    name: "반팔 마리나 셔츠",
    subname: "S/S MARINA SHIRT",
    category: ["top", "shirt"],
    gender: "male",
    price: 145000,
    src: ["./img/top/top_s_m_04/front_blue.jpg", "./img/top/top_s_m_04/back_blue.jpg"],
    color: ["blue", "black"],
    isOut: false,
    isBest: true,
    isNew: true,
    discountRate: 0
  },
  {
    id: "top_s_m_04",
    name: "여성 반팔 로빌리아 셔츠",
    subname: "W S/S LOVILIA SHIRT",
    category: ["top", "shirt"],
    gender: "female",
    price: 138000,
    src: ["./img/top/top_s_w_01/front.jpg", "./img/top/top_s_w_01/back.jpg"],
    color: ["blue"],
    isOut: false,
    isBest: true,
    isNew: true,
    discountRate: 0
  }
]

const itemList = [{
    id: "top_ts_m_01",
    name: "반팔 라이프가즈 티셔츠",
    subname: "S/S LIFEGUARDS T-SHIRT",
    stylecode: "CA23SSTSSS00002017",
    price: 75000,
    rating: 5,
    color: ["black", "white", "yellow"],
    colorSrc: [
      ["./img/top/top_ts_m_01/front_black.jpg", "./img/top/top_ts_m_01/back_black.jpg", "./img/top/top_ts_m_01/1_black.jpg", "./img/top/top_ts_m_01/2_black.jpg", "./img/top/top_ts_m_01/3_black.jpg", "./img/top/top_ts_m_01/4_black.jpg"],
      ["./img/top/top_ts_m_01/front_white.jpg", "./img/top/top_ts_m_01/back_white.jpg", "./img/top/top_ts_m_01/1_white.jpg", "./img/top/top_ts_m_01/2_white.jpg", "./img/top/top_ts_m_01/3_white.jpg", "./img/top/top_ts_m_01/4_white.jpg"],
      ["./img/top/top_ts_m_01/front_yellow.jpg", "./img/top/top_ts_m_01/back_yellow.jpg", "./img/top/top_ts_m_01/1_yellow.jpg", "./img/top/top_ts_m_01/2_yellow.jpg", "./img/top/top_ts_m_01/3_yellow.jpg", "./img/top/top_ts_m_01/4_yellow.jpg"]
    ],
    desc: ["S/S LIFEGUARDS T-SHIRT는 오가닉 코튼100% 싱글 저지 소재의 반팔 티셔츠입니다. 레귤러 핏이며, 정면에 그래픽 프린트가 있습니다.", "", "- 세탁 및 다림 시 그래픽의 손상 및 변형이 생길 수 있으므로, 뒤집어 세탁 및 다림을 권장합니다."],
    size: ["S", "M", "L", "XL", "XXL"],
    isOut: false,
    isBest: true,
    isNew: true,
    withItem: true,
    withItemID: ["bottom_short_m_01"],
    discountRate: 0
  },
  {
    id: "bottom_short_m_01",
    name: "로튼 쇼츠 베스탈",
    subname: "LAWTON SHORT VESTAL",
    stylecode: "CA23SSSTOT11185001",
    price: 148000,
    rating: 5,
    color: ["brown"],
    colorSrc: [
      ["./img/bottom/bottom_short_m_01/front_brown.jpg", "./img/bottom/bottom_short_m_01/1_brown.jpg", "./img/bottom/bottom_short_m_01/2_brown.jpg", "./img/bottom/bottom_short_m_01/3_brown.jpg", "./img/bottom/bottom_short_m_01/4_brown.jpg"]
    ],
    desc: ["LAWTON SHORT는 면98%, 라이크라® 2%  VESTAL 스트레치 트윌 소재의 반바지입니다. 릴렉스드 핏에 밑위는 로우 크로치입니다.", "허리 밴드는 신축성이 있으며 드로우 코드로 둘레 조절이 가능합니다. 후면 포켓에 스퀘어 라벨이 부착되어 있습니다."],
    size: ["S", "M", "L", "XL"],
    isOut: false,
    isBest: true,
    isNew: true,
    withItem: true,
    withItemID: ["top_ts_m_01"],
    discountRate: 0
  }
]

export {
  Lookbook_Data,
  shoppingList_Top,
  itemList
}